// swift-tools-version: 5.9
// MapMap - the iOS navigation SDK (binary-core distribution).
// Generated by release-ios.yml; do not edit by hand.
import PackageDescription

let package = Package(
    name: "MapMapKit",
    platforms: [
        .iOS("16.4")
    ],
    products: [
        .library(name: "MapMapKit", targets: ["MapMapKit"]),
        .library(name: "MapMapValhalla", targets: ["MapMapValhalla"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Rallista/valhalla-mobile.git", from: "0.5.1")
    ],
    targets: [
        .target(
            name: "MapMapKit",
            dependencies: ["MapMapFFI"],
            resources: [.process("Resources")]
        ),
        .target(
            name: "MapMapValhalla",
            dependencies: [
                "MapMapKit",
                .product(name: "Valhalla", package: "valhalla-mobile"),
            ]
        ),
        .binaryTarget(
            name: "MapMapFFI",
            url: "https://github.com/Mapmapai/mapmap-ios/releases/download/0.5.0/MapMapFFI.xcframework.zip",
            checksum: "ed4fcd2d7d8f3f0cefce379da47760d5133497f9cf703bb699598d80e6fb54ed"
        ),
    ]
)
