import AVFoundation
import Foundation

/// Prosody and earcon policy per `InstructionSeverity` — pure and
/// unit-testable anywhere (the platform wiring lives in ``VoiceGuidance``).
///
/// The core derives severity (see `InstructionSeverity` in
/// `crates/sn-nav-core`): `.info` for routine manoeuvres, `.warning` when
/// approaching a restriction (toll, ferry — and off-route), `.critical`
/// for prohibitions (ADR tunnel block, gate).
public struct VoiceProsody: Equatable, Sendable {
    /// `AVSpeechUtterance` rate (0–1 scale; the platform default is
    /// `AVSpeechUtteranceDefaultSpeechRate`).
    public let rate: Float
    /// Utterance pitch multiplier (1.0 = neutral).
    public let pitchMultiplier: Float
    /// Whether pending speech is stopped before this prompt.
    public let interrupt: Bool

    /// Prosody for `severity` at `baseRate` (defaults to the platform's
    /// default speech rate). Critical prompts speak slightly faster,
    /// clamped to the platform maximum.
    public static func prosody(
        for severity: InstructionSeverity,
        baseRate: Float = AVSpeechUtteranceDefaultSpeechRate
    ) -> VoiceProsody {
        switch severity {
        case .info:
            return VoiceProsody(rate: baseRate, pitchMultiplier: 1.0, interrupt: false)
        case .warning:
            return VoiceProsody(rate: baseRate, pitchMultiplier: 1.1, interrupt: false)
        case .critical:
            return VoiceProsody(
                rate: min(baseRate * 1.1, AVSpeechUtteranceMaximumSpeechRate),
                pitchMultiplier: 1.2,
                interrupt: true)
        }
    }

    /// The earcon resource name for `severity`, or `nil` when the
    /// severity plays none by default (info stays silent so a chime does
    /// not precede every routine manoeuvre). Assets are generated by
    /// `scripts/generate-earcons.py`.
    public static func earconName(for severity: InstructionSeverity) -> String? {
        switch severity {
        case .info: return nil
        case .warning: return "earcon-warning"
        case .critical: return "earcon-critical"
        }
    }

    /// URL of the earcon WAV inside MapMapKit's resource bundle, or `nil`
    /// for severities that play none.
    public static func earconURL(for severity: InstructionSeverity) -> URL? {
        guard let name = earconName(for: severity) else { return nil }
        return Bundle.module.url(forResource: name, withExtension: "wav")
    }
}

/// Ref-count of in-flight utterances, deciding when the shared audio
/// session may be deactivated (so ducked music comes back up) — pure and
/// unit-testable anywhere, like ``VoiceProsody``. The platform wiring in
/// ``VoiceGuidance`` mutates it under a lock: `AVSpeechSynthesizer`
/// delegate callbacks arrive on an arbitrary queue.
public struct SpeechSessionRefCount: Equatable, Sendable {
    /// Utterances handed to the synthesiser that have not yet finished
    /// or been cancelled.
    public private(set) var outstanding: Int = 0

    public init() {}

    /// Record one utterance handed to the synthesiser.
    public mutating func willSpeak() {
        outstanding += 1
    }

    /// Record one utterance finishing or being cancelled. Returns `true`
    /// when that was the last one — nothing is speaking or queued, so the
    /// audio session should be deactivated. Spurious callbacks after a
    /// ``reset()`` never trigger another deactivation.
    public mutating func didEnd() -> Bool {
        guard outstanding > 0 else { return false }
        outstanding -= 1
        return outstanding == 0
    }

    /// Clear everything (`stop()`). Returns `true` when there was
    /// anything outstanding — i.e. the session should be deactivated.
    public mutating func reset() -> Bool {
        let had = outstanding > 0
        outstanding = 0
        return had
    }
}

/// Spoken turn-by-turn guidance over `AVSpeechSynthesizer` (offline — the
/// platform voices synthesise on device).
///
/// Feed every ``NavigationState`` (or raw `GuidanceUpdate`) from
/// ``NavigationEngine/navigate(provider:)``:
///
/// ```swift
/// let voice = VoiceGuidance()
/// for try await state in await engine.navigate(provider: provider) {
///     voice.handle(state)
///     render(state)
/// }
/// ```
///
/// The core schedules each spoken prompt by its trigger distance and
/// repeats it on every update until it is superseded, so the speaking
/// rule is: announce each `utteranceId` exactly once, the first time it
/// appears. Severity maps to prosody and earcons via ``VoiceProsody``;
/// critical prompts stop pending speech. Off-route plays the warning
/// earcon once per episode. Observe ``isSpeaking`` /
/// ``onSpeakingChanged`` to reflect live speaking state in UI (e.g. a
/// pulsing voice icon). On iOS the audio session ducks other audio
/// around announcements (`.duckOthers` + `.voicePrompt`), so music dims
/// rather than stops — and is deactivated again once the last utterance
/// finishes, so music comes back to full volume instead of staying
/// ducked forever.
public final class VoiceGuidance: NSObject, AVSpeechSynthesizerDelegate {

    private let synthesizer = AVSpeechSynthesizer()
    private let language: String?
    private let baseRate: Float
    private var lastUtteranceId: String?
    private var offRouteAnnounced = false
    private var earconPlayer: AVAudioPlayer?
    /// Guards `sessionRefCount` and the stored speaking flag: delegate
    /// callbacks arrive on an arbitrary queue while `speak`/`stop` run on
    /// the caller's.
    private let sessionLock = NSLock()
    private var sessionRefCount = SpeechSessionRefCount()
    private var speaking = false

    /// Whether an utterance is currently being spoken or queued. Mirrors
    /// the transitions delivered to ``onSpeakingChanged``.
    public var isSpeaking: Bool {
        sessionLock.lock()
        defer { sessionLock.unlock() }
        return speaking
    }

    /// Called on every speaking-state transition: `true` when the first
    /// utterance of a burst starts, `false` once the last one finishes,
    /// is cancelled or ``stop()`` is called. May be invoked on an
    /// arbitrary queue (the synthesiser's delegate queue) — hop to the
    /// main actor before touching UI.
    public var onSpeakingChanged: ((Bool) -> Void)?

    /// Whether announcements are muted. Toggle freely mid-drive; muting
    /// also stops anything mid-utterance.
    public var muted: Bool = false {
        didSet {
            if muted { synthesizer.stopSpeaking(at: .immediate) }
        }
    }

    /// Announcement volume, 0–1 (applied to speech and earcons).
    public var volume: Float = 1.0 {
        didSet { volume = min(1.0, max(0.0, volume)) }
    }

    /// - Parameters:
    ///   - language: BCP 47 tag for the voice, e.g. `en-GB`. `nil` keeps
    ///     the device default voice.
    ///   - baseRate: base `AVSpeechUtterance` rate (platform default when
    ///     omitted).
    public init(
        language: String? = nil,
        baseRate: Float = AVSpeechUtteranceDefaultSpeechRate
    ) {
        self.language = language
        self.baseRate = baseRate
        super.init()
        synthesizer.delegate = self
        #if os(iOS)
            // Navigation prompts duck (never stop) whatever else plays.
            try? AVAudioSession.sharedInstance().setCategory(
                .playback,
                mode: .voicePrompt,
                options: [.duckOthers, .interruptSpokenAudioAndMixWithOthers])
        #endif
    }

    /// Consume one guidance update. Cheap; call it for every emission of
    /// ``NavigationEngine/navigate(provider:)``.
    public func handle(_ update: GuidanceUpdate) {
        switch update {
        case .navigating(_, _, _, _, _, _, _, let spoken, _, let severity, _):
            offRouteAnnounced = false
            guard let spoken, spoken.utteranceId != lastUtteranceId else { return }
            // Record before the mute check so prompts seen while muted are
            // never replayed, stale, on unmute.
            lastUtteranceId = spoken.utteranceId
            speak(spoken, severity: severity)
        case .offRoute:
            if !offRouteAnnounced {
                offRouteAnnounced = true
                playEarcon(for: .warning)
            }
        case .arrived:
            break // the arrival prompt arrived as `spoken`
        }
    }

    /// Convenience overload for ``NavigationEngine/navigate(provider:)``
    /// emissions.
    public func handle(_ state: NavigationState) {
        handle(state.update)
    }

    /// Stop speech and release the earcon player. Deactivates the audio
    /// session (un-ducking whatever else plays) when anything was live.
    public func stop() {
        sessionLock.lock()
        let hadOutstanding = sessionRefCount.reset()
        let stoppedSpeaking = speaking
        speaking = false
        sessionLock.unlock()
        synthesizer.stopSpeaking(at: .immediate)
        earconPlayer?.stop()
        earconPlayer = nil
        lastUtteranceId = nil
        offRouteAnnounced = false
        if hadOutstanding { deactivateSession() }
        if stoppedSpeaking { onSpeakingChanged?(false) }
    }

    // MARK: - AVSpeechSynthesizerDelegate

    public func speechSynthesizer(
        _ synthesizer: AVSpeechSynthesizer,
        didFinish utterance: AVSpeechUtterance
    ) {
        utteranceEnded()
    }

    public func speechSynthesizer(
        _ synthesizer: AVSpeechSynthesizer,
        didCancel utterance: AVSpeechUtterance
    ) {
        utteranceEnded()
    }

    /// Called from delegate callbacks (arbitrary queue): once nothing is
    /// speaking or queued, hand the audio session back so ducked audio
    /// returns to full volume.
    private func utteranceEnded() {
        sessionLock.lock()
        let idle = sessionRefCount.didEnd()
        let stoppedSpeaking = idle && speaking
        if idle { speaking = false }
        sessionLock.unlock()
        if idle { deactivateSession() }
        if stoppedSpeaking { onSpeakingChanged?(false) }
    }

    private func deactivateSession() {
        #if os(iOS)
            try? AVAudioSession.sharedInstance().setActive(
                false, options: .notifyOthersOnDeactivation)
        #endif
    }

    private func speak(_ spoken: SpokenPrompt, severity: InstructionSeverity) {
        guard !muted else { return }
        let prosody = VoiceProsody.prosody(for: severity, baseRate: baseRate)
        // Count the new utterance before any interrupt cancels the old
        // one, so the ref-count never dips to zero (and deactivates the
        // session) in the middle of a critical hand-over.
        sessionLock.lock()
        sessionRefCount.willSpeak()
        let startedSpeaking = !speaking
        speaking = true
        sessionLock.unlock()
        if startedSpeaking { onSpeakingChanged?(true) }
        if prosody.interrupt {
            synthesizer.stopSpeaking(at: .immediate)
        }
        playEarcon(for: severity)
        #if os(iOS)
            try? AVAudioSession.sharedInstance().setActive(true)
        #endif
        // AVSpeechUtterance takes plain text (Apple's SSML support is
        // representation-only); the core always supplies the plain form.
        let utterance = AVSpeechUtterance(string: spoken.text)
        if let language, let voice = AVSpeechSynthesisVoice(language: language) {
            utterance.voice = voice
        }
        utterance.rate = prosody.rate
        utterance.pitchMultiplier = prosody.pitchMultiplier
        utterance.volume = volume
        synthesizer.speak(utterance)
    }

    private func playEarcon(for severity: InstructionSeverity) {
        guard !muted, let url = VoiceProsody.earconURL(for: severity) else { return }
        guard let player = try? AVAudioPlayer(contentsOf: url) else { return }
        earconPlayer = player
        player.volume = volume
        player.play()
    }
}
