import AVFoundation
import Foundation

/// Prosody and earcon policy per `InstructionSeverity` — pure and
/// unit-testable anywhere (the platform wiring lives in ``VoiceGuidance``).
///
/// The core derives severity (see `InstructionSeverity` in
/// `crates/sn-nav-core`): `.info` for routine manoeuvres, `.warning` when
/// approaching a restriction (toll, ferry — and off-route), `.critical`
/// for prohibitions (ADR tunnel block, gate).
public struct VoiceProsody: Equatable, Sendable {
    /// `AVSpeechUtterance` rate (0–1 scale; the platform default is
    /// `AVSpeechUtteranceDefaultSpeechRate`).
    public let rate: Float
    /// Utterance pitch multiplier (1.0 = neutral).
    public let pitchMultiplier: Float
    /// Whether pending speech is stopped before this prompt.
    public let interrupt: Bool

    /// Prosody for `severity` at `baseRate` (defaults to the platform's
    /// default speech rate). Critical prompts speak slightly faster,
    /// clamped to the platform maximum.
    public static func prosody(
        for severity: InstructionSeverity,
        baseRate: Float = AVSpeechUtteranceDefaultSpeechRate
    ) -> VoiceProsody {
        switch severity {
        case .info:
            return VoiceProsody(rate: baseRate, pitchMultiplier: 1.0, interrupt: false)
        case .warning:
            return VoiceProsody(rate: baseRate, pitchMultiplier: 1.1, interrupt: false)
        case .critical:
            return VoiceProsody(
                rate: min(baseRate * 1.1, AVSpeechUtteranceMaximumSpeechRate),
                pitchMultiplier: 1.2,
                interrupt: true)
        }
    }

    /// The earcon resource name for `severity`, or `nil` when the
    /// severity plays none by default (info stays silent so a chime does
    /// not precede every routine manoeuvre). Assets are generated by
    /// `scripts/generate-earcons.py`.
    public static func earconName(for severity: InstructionSeverity) -> String? {
        switch severity {
        case .info: return nil
        case .warning: return "earcon-warning"
        case .critical: return "earcon-critical"
        }
    }

    /// URL of the earcon WAV inside MapMapKit's resource bundle, or `nil`
    /// for severities that play none.
    public static func earconURL(for severity: InstructionSeverity) -> URL? {
        guard let name = earconName(for: severity) else { return nil }
        return Bundle.module.url(forResource: name, withExtension: "wav")
    }
}

/// Spoken turn-by-turn guidance over `AVSpeechSynthesizer` (offline — the
/// platform voices synthesise on device).
///
/// Feed every ``NavigationState`` (or raw `GuidanceUpdate`) from
/// ``NavigationEngine/navigate(provider:)``:
///
/// ```swift
/// let voice = VoiceGuidance()
/// for try await state in await engine.navigate(provider: provider) {
///     voice.handle(state)
///     render(state)
/// }
/// ```
///
/// The core schedules each spoken prompt by its trigger distance and
/// repeats it on every update until it is superseded, so the speaking
/// rule is: announce each `utteranceId` exactly once, the first time it
/// appears. Severity maps to prosody and earcons via ``VoiceProsody``;
/// critical prompts stop pending speech. Off-route plays the warning
/// earcon once per episode. On iOS the audio session ducks other audio
/// around announcements (`.duckOthers` + `.voicePrompt`), so music dims
/// rather than stops.
public final class VoiceGuidance {

    private let synthesizer = AVSpeechSynthesizer()
    private let language: String?
    private let baseRate: Float
    private var lastUtteranceId: String?
    private var offRouteAnnounced = false
    private var earconPlayer: AVAudioPlayer?

    /// Whether announcements are muted. Toggle freely mid-drive; muting
    /// also stops anything mid-utterance.
    public var muted: Bool = false {
        didSet {
            if muted { synthesizer.stopSpeaking(at: .immediate) }
        }
    }

    /// Announcement volume, 0–1 (applied to speech and earcons).
    public var volume: Float = 1.0 {
        didSet { volume = min(1.0, max(0.0, volume)) }
    }

    /// - Parameters:
    ///   - language: BCP 47 tag for the voice, e.g. `en-GB`. `nil` keeps
    ///     the device default voice.
    ///   - baseRate: base `AVSpeechUtterance` rate (platform default when
    ///     omitted).
    public init(
        language: String? = nil,
        baseRate: Float = AVSpeechUtteranceDefaultSpeechRate
    ) {
        self.language = language
        self.baseRate = baseRate
        #if os(iOS)
            // Navigation prompts duck (never stop) whatever else plays.
            try? AVAudioSession.sharedInstance().setCategory(
                .playback,
                mode: .voicePrompt,
                options: [.duckOthers, .interruptSpokenAudioAndMixWithOthers])
        #endif
    }

    /// Consume one guidance update. Cheap; call it for every emission of
    /// ``NavigationEngine/navigate(provider:)``.
    public func handle(_ update: GuidanceUpdate) {
        switch update {
        case .navigating(_, _, _, _, _, _, _, let spoken, _, let severity):
            offRouteAnnounced = false
            guard let spoken, spoken.utteranceId != lastUtteranceId else { return }
            // Record before the mute check so prompts seen while muted are
            // never replayed, stale, on unmute.
            lastUtteranceId = spoken.utteranceId
            speak(spoken, severity: severity)
        case .offRoute:
            if !offRouteAnnounced {
                offRouteAnnounced = true
                playEarcon(for: .warning)
            }
        case .arrived:
            break // the arrival prompt arrived as `spoken`
        }
    }

    /// Convenience overload for ``NavigationEngine/navigate(provider:)``
    /// emissions.
    public func handle(_ state: NavigationState) {
        handle(state.update)
    }

    /// Stop speech and release the earcon player.
    public func stop() {
        synthesizer.stopSpeaking(at: .immediate)
        earconPlayer?.stop()
        earconPlayer = nil
        lastUtteranceId = nil
        offRouteAnnounced = false
    }

    private func speak(_ spoken: SpokenPrompt, severity: InstructionSeverity) {
        guard !muted else { return }
        let prosody = VoiceProsody.prosody(for: severity, baseRate: baseRate)
        if prosody.interrupt {
            synthesizer.stopSpeaking(at: .immediate)
        }
        playEarcon(for: severity)
        #if os(iOS)
            try? AVAudioSession.sharedInstance().setActive(true)
        #endif
        // AVSpeechUtterance takes plain text (Apple's SSML support is
        // representation-only); the core always supplies the plain form.
        let utterance = AVSpeechUtterance(string: spoken.text)
        if let language, let voice = AVSpeechSynthesisVoice(language: language) {
            utterance.voice = voice
        }
        utterance.rate = prosody.rate
        utterance.pitchMultiplier = prosody.pitchMultiplier
        utterance.volume = volume
        synthesizer.speak(utterance)
    }

    private func playEarcon(for severity: InstructionSeverity) {
        guard !muted, let url = VoiceProsody.earconURL(for: severity) else { return }
        guard let player = try? AVAudioPlayer(contentsOf: url) else { return }
        earconPlayer = player
        player.volume = volume
        player.play()
    }
}
